{{ if not .Values.admin.secured }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}-datasources
  labels:
    grafana_datasource: {{ template "grafana.fullname" . }}
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: orion-datasource
        type: orion-datasource
        access: proxy
        orgId: 1
        uid: "2"
        url: {{ .Values.datasources.orion.url | default "http://orion:1026" }}
        jsonData:
          orionPaginationLimit: 1000
        basicAuth: false
        withCredentials: false
        isDefault: false
        version: 1
        editable: true
      - name: timescale-datasource  
        type: postgres
        access: proxy
        orgId: 1
        uid: "3"
        user: {{ .Values.datasources.timescale.credentials.username | default "admin" }}
        url: {{ .Values.datasources.timescale.url | default "tsdb:5432" }}
        database: {{ .Values.datasources.timescale.database | default "postgres" }}
        secureJsonData:
          password: {{ .Values.datasources.timescale.credentials.password | default "admin" }}
        basicAuth: false
        withCredentials: false
        isDefault: false
        jsonData:
          sslmode: disable
          postgresVersion: 1200
          timescaledb: true
        version: 1
        editable: true 
{{ end }}