apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - clusterroles/
  - clusterrolebindings/
  - operatorgroups/
  - subscriptions/
  - argocds/
  - externalsecrets/
  - serviceaccounts/