apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes to deploy Keycloak using the official Keycloak Operator.
type: application
version: 1.0.0
appVersion: "17.0.1" # Keycloak 17.0.1 PostgreSQL 14.2.0
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
keywords:
  - keycloak
  - operator
sources:
  - https://github.com/FIWARE-Ops/marinera
maintainers:
  - name: Felipe Roca
    email: felipe@hopu.org
  - name: Alvaro Lopez
    email: alopezme@redhat.com
  - name: Stefan Wiedemann 
    email: stefan.wiedemann@fiware.org
dependencies:
- name: keycloak
  version: 8.0.0 
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami


